package com.mmdt.syna;

import com.fima.glowpadview.C0092R;
import org.linphone.C0282R;

/* renamed from: com.mmdt.syna.c */
public final class R {

    /* renamed from: com.mmdt.syna.c.a */
    public static final class R {
        public static final int[] ActionBar;
        public static final int[] ActionBarLayout;
        public static final int ActionBarLayout_android_layout_gravity = 0;
        public static final int[] ActionBarWindow;
        public static final int ActionBarWindow_windowActionBar = 0;
        public static final int ActionBarWindow_windowActionBarOverlay = 1;
        public static final int ActionBarWindow_windowFixedHeightMajor = 6;
        public static final int ActionBarWindow_windowFixedHeightMinor = 4;
        public static final int ActionBarWindow_windowFixedWidthMajor = 3;
        public static final int ActionBarWindow_windowFixedWidthMinor = 5;
        public static final int ActionBarWindow_windowSplitActionBar = 2;
        public static final int ActionBar_background = 10;
        public static final int ActionBar_backgroundSplit = 12;
        public static final int ActionBar_backgroundStacked = 11;
        public static final int ActionBar_customNavigationLayout = 13;
        public static final int ActionBar_displayOptions = 3;
        public static final int ActionBar_divider = 9;
        public static final int ActionBar_height = 1;
        public static final int ActionBar_homeLayout = 14;
        public static final int ActionBar_icon = 7;
        public static final int ActionBar_indeterminateProgressStyle = 16;
        public static final int ActionBar_itemPadding = 18;
        public static final int ActionBar_logo = 8;
        public static final int ActionBar_navigationMode = 2;
        public static final int ActionBar_progressBarPadding = 17;
        public static final int ActionBar_progressBarStyle = 15;
        public static final int ActionBar_subtitle = 4;
        public static final int ActionBar_subtitleTextStyle = 6;
        public static final int ActionBar_title = 0;
        public static final int ActionBar_titleTextStyle = 5;
        public static final int[] ActionMenuItemView;
        public static final int ActionMenuItemView_android_minWidth = 0;
        public static final int[] ActionMenuView;
        public static final int[] ActionMode;
        public static final int ActionMode_background = 3;
        public static final int ActionMode_backgroundSplit = 4;
        public static final int ActionMode_height = 0;
        public static final int ActionMode_subtitleTextStyle = 2;
        public static final int ActionMode_titleTextStyle = 1;
        public static final int[] ActivityChooserView;
        public static final int ActivityChooserView_expandActivityOverflowButtonDrawable = 1;
        public static final int ActivityChooserView_initialActivityCount = 0;
        public static final int[] AnalogClock;
        public static final int AnalogClock_jewelColor = 2;
        public static final int AnalogClock_jewelOffset = 1;
        public static final int AnalogClock_jewelRadius = 0;
        public static final int[] AutofitTextView;
        public static final int AutofitTextView_minTextSize = 0;
        public static final int AutofitTextView_precision = 1;
        public static final int AutofitTextView_sizeToFit = 2;
        public static final int[] AvatarWithShadow;
        public static final int AvatarWithShadow_picture = 0;
        public static final int[] CirclePageIndicator;
        public static final int CirclePageIndicator_android_background = 1;
        public static final int CirclePageIndicator_android_orientation = 0;
        public static final int CirclePageIndicator_centered = 2;
        public static final int CirclePageIndicator_fillColor = 4;
        public static final int CirclePageIndicator_indicatorRadius = 6;
        public static final int CirclePageIndicator_pageColor = 5;
        public static final int CirclePageIndicator_snap = 7;
        public static final int CirclePageIndicator_strokeColor = 8;
        public static final int CirclePageIndicator_strokeWidth = 3;
        public static final int[] CompatTextView;
        public static final int CompatTextView_textAllCaps = 0;
        public static final int[] CropImageView;
        public static final int CropImageView_aspectRatioX = 2;
        public static final int CropImageView_aspectRatioY = 3;
        public static final int CropImageView_fixAspectRatio = 1;
        public static final int CropImageView_guidelines = 0;
        public static final int CropImageView_imageResource = 4;
        public static final int[] GlowPadView;
        public static final int GlowPadView_alwaysTrackFinger = 13;
        public static final int GlowPadView_android_gravity = 0;
        public static final int GlowPadView_directionDescriptions = 3;
        public static final int GlowPadView_feedbackCount = 12;
        public static final int GlowPadView_glowRadius = 9;
        public static final int GlowPadView_handleDrawable = 4;
        public static final int GlowPadView_innerRadius = 7;
        public static final int GlowPadView_outerRadius = 8;
        public static final int GlowPadView_outerRingDrawable = 5;
        public static final int GlowPadView_pointDrawable = 6;
        public static final int GlowPadView_snapMargin = 11;
        public static final int GlowPadView_targetDescriptions = 2;
        public static final int GlowPadView_targetDrawables = 1;
        public static final int GlowPadView_vibrationDuration = 10;
        public static final int[] LinePageIndicator;
        public static final int LinePageIndicator_android_background = 0;
        public static final int LinePageIndicator_centered = 1;
        public static final int LinePageIndicator_gapWidth = 6;
        public static final int LinePageIndicator_lineWidth = 5;
        public static final int LinePageIndicator_selectedColor = 2;
        public static final int LinePageIndicator_strokeWidth = 3;
        public static final int LinePageIndicator_unselectedColor = 4;
        public static final int[] LinearLayoutICS;
        public static final int LinearLayoutICS_divider = 0;
        public static final int LinearLayoutICS_dividerPadding = 2;
        public static final int LinearLayoutICS_showDividers = 1;
        public static final int[] MenuGroup;
        public static final int MenuGroup_android_checkableBehavior = 5;
        public static final int MenuGroup_android_enabled = 0;
        public static final int MenuGroup_android_id = 1;
        public static final int MenuGroup_android_menuCategory = 3;
        public static final int MenuGroup_android_orderInCategory = 4;
        public static final int MenuGroup_android_visible = 2;
        public static final int[] MenuItem;
        public static final int MenuItem_actionLayout = 14;
        public static final int MenuItem_actionProviderClass = 16;
        public static final int MenuItem_actionViewClass = 15;
        public static final int MenuItem_android_alphabeticShortcut = 9;
        public static final int MenuItem_android_checkable = 11;
        public static final int MenuItem_android_checked = 3;
        public static final int MenuItem_android_enabled = 1;
        public static final int MenuItem_android_icon = 0;
        public static final int MenuItem_android_id = 2;
        public static final int MenuItem_android_menuCategory = 5;
        public static final int MenuItem_android_numericShortcut = 10;
        public static final int MenuItem_android_onClick = 12;
        public static final int MenuItem_android_orderInCategory = 6;
        public static final int MenuItem_android_title = 7;
        public static final int MenuItem_android_titleCondensed = 8;
        public static final int MenuItem_android_visible = 4;
        public static final int MenuItem_showAsAction = 13;
        public static final int[] MenuView;
        public static final int MenuView_android_headerBackground = 4;
        public static final int MenuView_android_horizontalDivider = 2;
        public static final int MenuView_android_itemBackground = 5;
        public static final int MenuView_android_itemIconDisabledAlpha = 6;
        public static final int MenuView_android_itemTextAppearance = 1;
        public static final int MenuView_android_preserveIconSpacing = 7;
        public static final int MenuView_android_verticalDivider = 3;
        public static final int MenuView_android_windowAnimationStyle = 0;
        public static final int[] Numpad;
        public static final int Numpad_play_dtmf = 0;
        public static final int[] PagerSlidingTabStrip;
        public static final int PagerSlidingTabStrip_pstsDividerColor = 2;
        public static final int PagerSlidingTabStrip_pstsDividerPadding = 5;
        public static final int PagerSlidingTabStrip_pstsIndicatorColor = 0;
        public static final int PagerSlidingTabStrip_pstsIndicatorHeight = 3;
        public static final int PagerSlidingTabStrip_pstsScrollOffset = 7;
        public static final int PagerSlidingTabStrip_pstsShouldExpand = 9;
        public static final int PagerSlidingTabStrip_pstsTabBackground = 8;
        public static final int PagerSlidingTabStrip_pstsTabPaddingLeftRight = 6;
        public static final int PagerSlidingTabStrip_pstsTextAllCaps = 10;
        public static final int PagerSlidingTabStrip_pstsUnderlineColor = 1;
        public static final int PagerSlidingTabStrip_pstsUnderlineHeight = 4;
        public static final int[] ProgressWheel;
        public static final int ProgressWheel_barColor = 3;
        public static final int ProgressWheel_barLength = 11;
        public static final int ProgressWheel_barWidth = 10;
        public static final int ProgressWheel_circleColor = 8;
        public static final int ProgressWheel_contourColor = 12;
        public static final int ProgressWheel_contourSize = 13;
        public static final int ProgressWheel_delayMillis = 7;
        public static final int ProgressWheel_radius = 9;
        public static final int ProgressWheel_rimColor = 4;
        public static final int ProgressWheel_rimWidth = 5;
        public static final int ProgressWheel_spinSpeed = 6;
        public static final int ProgressWheel_text = 0;
        public static final int ProgressWheel_textColor = 1;
        public static final int ProgressWheel_textSize = 2;
        public static final int[] PullToRefresh;
        public static final int PullToRefresh_ptrAdapterViewBackground = 16;
        public static final int PullToRefresh_ptrAnimationStyle = 12;
        public static final int PullToRefresh_ptrDrawable = 6;
        public static final int PullToRefresh_ptrDrawableBottom = 18;
        public static final int PullToRefresh_ptrDrawableEnd = 8;
        public static final int PullToRefresh_ptrDrawableStart = 7;
        public static final int PullToRefresh_ptrDrawableTop = 17;
        public static final int PullToRefresh_ptrHeaderBackground = 1;
        public static final int PullToRefresh_ptrHeaderSubTextColor = 3;
        public static final int PullToRefresh_ptrHeaderTextAppearance = 10;
        public static final int PullToRefresh_ptrHeaderTextColor = 2;
        public static final int PullToRefresh_ptrListViewExtrasEnabled = 14;
        public static final int PullToRefresh_ptrMode = 4;
        public static final int PullToRefresh_ptrOverScroll = 9;
        public static final int PullToRefresh_ptrRefreshableViewBackground = 0;
        public static final int PullToRefresh_ptrRotateDrawableWhilePulling = 15;
        public static final int PullToRefresh_ptrScrollingWhileRefreshingEnabled = 13;
        public static final int PullToRefresh_ptrShowIndicator = 5;
        public static final int PullToRefresh_ptrSubHeaderTextAppearance = 11;
        public static final int[] RobotoAutoCompleteTextView;
        public static final int RobotoAutoCompleteTextView_fontFamily = 1;
        public static final int RobotoAutoCompleteTextView_textStyle = 3;
        public static final int RobotoAutoCompleteTextView_textWeight = 2;
        public static final int RobotoAutoCompleteTextView_typeface = 0;
        public static final int[] RobotoButton;
        public static final int RobotoButton_fontFamily = 1;
        public static final int RobotoButton_textStyle = 3;
        public static final int RobotoButton_textWeight = 2;
        public static final int RobotoButton_typeface = 0;
        public static final int[] RobotoCheckBox;
        public static final int RobotoCheckBox_fontFamily = 1;
        public static final int RobotoCheckBox_textStyle = 3;
        public static final int RobotoCheckBox_textWeight = 2;
        public static final int RobotoCheckBox_typeface = 0;
        public static final int[] RobotoCheckedTextView;
        public static final int RobotoCheckedTextView_fontFamily = 1;
        public static final int RobotoCheckedTextView_textStyle = 3;
        public static final int RobotoCheckedTextView_textWeight = 2;
        public static final int RobotoCheckedTextView_typeface = 0;
        public static final int[] RobotoChronometer;
        public static final int RobotoChronometer_fontFamily = 1;
        public static final int RobotoChronometer_textStyle = 3;
        public static final int RobotoChronometer_textWeight = 2;
        public static final int RobotoChronometer_typeface = 0;
        public static final int[] RobotoCompoundButton;
        public static final int RobotoCompoundButton_fontFamily = 1;
        public static final int RobotoCompoundButton_textStyle = 3;
        public static final int RobotoCompoundButton_textWeight = 2;
        public static final int RobotoCompoundButton_typeface = 0;
        public static final int[] RobotoDigitalClock;
        public static final int RobotoDigitalClock_fontFamily = 1;
        public static final int RobotoDigitalClock_textStyle = 3;
        public static final int RobotoDigitalClock_textWeight = 2;
        public static final int RobotoDigitalClock_typeface = 0;
        public static final int[] RobotoEditText;
        public static final int RobotoEditText_fontFamily = 1;
        public static final int RobotoEditText_textStyle = 3;
        public static final int RobotoEditText_textWeight = 2;
        public static final int RobotoEditText_typeface = 0;
        public static final int[] RobotoExtractEditText;
        public static final int RobotoExtractEditText_fontFamily = 1;
        public static final int RobotoExtractEditText_textStyle = 3;
        public static final int RobotoExtractEditText_textWeight = 2;
        public static final int RobotoExtractEditText_typeface = 0;
        public static final int[] RobotoMultiAutoCompleteTextView;
        public static final int RobotoMultiAutoCompleteTextView_fontFamily = 1;
        public static final int RobotoMultiAutoCompleteTextView_textStyle = 3;
        public static final int RobotoMultiAutoCompleteTextView_textWeight = 2;
        public static final int RobotoMultiAutoCompleteTextView_typeface = 0;
        public static final int[] RobotoRadioButton;
        public static final int RobotoRadioButton_fontFamily = 1;
        public static final int RobotoRadioButton_textStyle = 3;
        public static final int RobotoRadioButton_textWeight = 2;
        public static final int RobotoRadioButton_typeface = 0;
        public static final int[] RobotoSwitch;
        public static final int RobotoSwitch_fontFamily = 1;
        public static final int RobotoSwitch_textStyle = 3;
        public static final int RobotoSwitch_textWeight = 2;
        public static final int RobotoSwitch_typeface = 0;
        public static final int[] RobotoTextClock;
        public static final int RobotoTextClock_fontFamily = 1;
        public static final int RobotoTextClock_textStyle = 3;
        public static final int RobotoTextClock_textWeight = 2;
        public static final int RobotoTextClock_typeface = 0;
        public static final int[] RobotoTextView;
        public static final int RobotoTextView_fontFamily = 1;
        public static final int RobotoTextView_textStyle = 3;
        public static final int RobotoTextView_textWeight = 2;
        public static final int RobotoTextView_typeface = 0;
        public static final int[] RobotoToggleButton;
        public static final int RobotoToggleButton_fontFamily = 1;
        public static final int RobotoToggleButton_textStyle = 3;
        public static final int RobotoToggleButton_textWeight = 2;
        public static final int RobotoToggleButton_typeface = 0;
        public static final int[] SearchView;
        public static final int SearchView_android_imeOptions = 2;
        public static final int SearchView_android_inputType = 1;
        public static final int SearchView_android_maxWidth = 0;
        public static final int SearchView_iconifiedByDefault = 3;
        public static final int SearchView_queryHint = 4;
        public static final int[] SlidingDrawer;
        public static final int SlidingDrawer_content = 2;
        public static final int SlidingDrawer_direction = 0;
        public static final int SlidingDrawer_handle = 1;
        public static final int[] SlidingTab;
        public static final int SlidingTab_orientation = 0;
        public static final int[] Spinner;
        public static final int Spinner_android_dropDownHorizontalOffset = 4;
        public static final int Spinner_android_dropDownSelector = 1;
        public static final int Spinner_android_dropDownVerticalOffset = 5;
        public static final int Spinner_android_dropDownWidth = 3;
        public static final int Spinner_android_gravity = 0;
        public static final int Spinner_android_popupBackground = 2;
        public static final int Spinner_disableChildrenWhenDisabled = 9;
        public static final int Spinner_popupPromptView = 8;
        public static final int Spinner_prompt = 6;
        public static final int Spinner_spinnerMode = 7;
        public static final int[] SwipeListView;
        public static final int SwipeListView_swipeActionLeft = 8;
        public static final int SwipeListView_swipeActionRight = 9;
        public static final int SwipeListView_swipeAnimationTime = 1;
        public static final int SwipeListView_swipeBackView = 6;
        public static final int SwipeListView_swipeCloseAllItemsWhenMoveList = 4;
        public static final int SwipeListView_swipeDrawableChecked = 10;
        public static final int SwipeListView_swipeDrawableUnchecked = 11;
        public static final int SwipeListView_swipeFrontView = 5;
        public static final int SwipeListView_swipeMode = 7;
        public static final int SwipeListView_swipeOffsetLeft = 2;
        public static final int SwipeListView_swipeOffsetRight = 3;
        public static final int SwipeListView_swipeOpenOnLongPress = 0;
        public static final int[] Theme;
        public static final int Theme_actionDropDownStyle = 0;
        public static final int Theme_dropdownListPreferredItemHeight = 1;
        public static final int Theme_listChoiceBackgroundIndicator = 5;
        public static final int Theme_panelMenuListTheme = 4;
        public static final int Theme_panelMenuListWidth = 3;
        public static final int Theme_popupMenuStyle = 2;
        public static final int[] TitlePageIndicator;
        public static final int TitlePageIndicator_android_background = 2;
        public static final int TitlePageIndicator_android_textColor = 1;
        public static final int TitlePageIndicator_android_textSize = 0;
        public static final int TitlePageIndicator_clipPadding = 4;
        public static final int TitlePageIndicator_footerColor = 5;
        public static final int TitlePageIndicator_footerIndicatorHeight = 8;
        public static final int TitlePageIndicator_footerIndicatorStyle = 7;
        public static final int TitlePageIndicator_footerIndicatorUnderlinePadding = 9;
        public static final int TitlePageIndicator_footerLineHeight = 6;
        public static final int TitlePageIndicator_footerPadding = 10;
        public static final int TitlePageIndicator_linePosition = 11;
        public static final int TitlePageIndicator_selectedBold = 12;
        public static final int TitlePageIndicator_selectedColor = 3;
        public static final int TitlePageIndicator_titlePadding = 13;
        public static final int TitlePageIndicator_topPadding = 14;
        public static final int[] UnderlinePageIndicator;
        public static final int UnderlinePageIndicator_android_background = 0;
        public static final int UnderlinePageIndicator_fadeDelay = 3;
        public static final int UnderlinePageIndicator_fadeLength = 4;
        public static final int UnderlinePageIndicator_fades = 2;
        public static final int UnderlinePageIndicator_selectedColor = 1;
        public static final int[] View;
        public static final int[] ViewPagerIndicator;
        public static final int ViewPagerIndicator_vpiCirclePageIndicatorStyle = 0;
        public static final int ViewPagerIndicator_vpiIconPageIndicatorStyle = 1;
        public static final int ViewPagerIndicator_vpiLinePageIndicatorStyle = 2;
        public static final int ViewPagerIndicator_vpiTabPageIndicatorStyle = 4;
        public static final int ViewPagerIndicator_vpiTitlePageIndicatorStyle = 3;
        public static final int ViewPagerIndicator_vpiUnderlinePageIndicatorStyle = 5;
        public static final int View_android_focusable = 0;
        public static final int View_paddingEnd = 2;
        public static final int View_paddingStart = 1;

        static {
            ActionBar = new int[]{com.viewpagerindicator.R.R.title, com.viewpagerindicator.R.R.height, com.viewpagerindicator.R.R.navigationMode, com.viewpagerindicator.R.R.displayOptions, com.viewpagerindicator.R.R.subtitle, com.viewpagerindicator.R.R.titleTextStyle, com.viewpagerindicator.R.R.subtitleTextStyle, com.viewpagerindicator.R.R.icon, com.viewpagerindicator.R.R.logo, com.viewpagerindicator.R.R.divider, com.viewpagerindicator.R.R.background, com.viewpagerindicator.R.R.backgroundStacked, com.viewpagerindicator.R.R.backgroundSplit, com.viewpagerindicator.R.R.customNavigationLayout, com.viewpagerindicator.R.R.homeLayout, com.viewpagerindicator.R.R.progressBarStyle, com.viewpagerindicator.R.R.indeterminateProgressStyle, com.viewpagerindicator.R.R.progressBarPadding, com.viewpagerindicator.R.R.itemPadding};
            int[] iArr = new int[View_paddingStart];
            iArr[View_android_focusable] = 16842931;
            ActionBarLayout = iArr;
            ActionBarWindow = new int[]{com.viewpagerindicator.R.R.windowActionBar, com.viewpagerindicator.R.R.windowActionBarOverlay, com.viewpagerindicator.R.R.windowSplitActionBar, com.viewpagerindicator.R.R.windowFixedWidthMajor, com.viewpagerindicator.R.R.windowFixedHeightMinor, com.viewpagerindicator.R.R.windowFixedWidthMinor, com.viewpagerindicator.R.R.windowFixedHeightMajor};
            iArr = new int[View_paddingStart];
            iArr[View_android_focusable] = 16843071;
            ActionMenuItemView = iArr;
            ActionMenuView = new int[View_android_focusable];
            ActionMode = new int[]{com.viewpagerindicator.R.R.height, com.viewpagerindicator.R.R.titleTextStyle, com.viewpagerindicator.R.R.subtitleTextStyle, com.viewpagerindicator.R.R.background, com.viewpagerindicator.R.R.backgroundSplit};
            ActivityChooserView = new int[]{com.viewpagerindicator.R.R.initialActivityCount, com.viewpagerindicator.R.R.expandActivityOverflowButtonDrawable};
            AnalogClock = new int[]{C0092R.attr.jewelRadius, C0092R.attr.jewelOffset, C0092R.attr.jewelColor};
            AutofitTextView = new int[]{2130772184, 2130772185, 2130772186};
            iArr = new int[View_paddingStart];
            iArr[View_android_focusable] = C0282R.attr.picture;
            AvatarWithShadow = iArr;
            CirclePageIndicator = new int[]{16842948, 16842964, com.viewpagerindicator.R.R.centered, com.viewpagerindicator.R.R.strokeWidth, com.viewpagerindicator.R.R.fillColor, com.viewpagerindicator.R.R.pageColor, com.viewpagerindicator.R.R.indicatorRadius, com.viewpagerindicator.R.R.snap, com.viewpagerindicator.R.R.strokeColor};
            iArr = new int[View_paddingStart];
            iArr[View_android_focusable] = com.viewpagerindicator.R.R.textAllCaps;
            CompatTextView = iArr;
            CropImageView = new int[]{2130772115, 2130772116, 2130772117, 2130772118, 2130772119};
            GlowPadView = new int[]{16842927, C0092R.attr.targetDrawables, C0092R.attr.targetDescriptions, C0092R.attr.directionDescriptions, C0092R.attr.handleDrawable, C0092R.attr.outerRingDrawable, C0092R.attr.pointDrawable, C0092R.attr.innerRadius, C0092R.attr.outerRadius, C0092R.attr.glowRadius, C0092R.attr.vibrationDuration, C0092R.attr.snapMargin, C0092R.attr.feedbackCount, C0092R.attr.alwaysTrackFinger};
            LinePageIndicator = new int[]{16842964, com.viewpagerindicator.R.R.centered, com.viewpagerindicator.R.R.selectedColor, com.viewpagerindicator.R.R.strokeWidth, com.viewpagerindicator.R.R.unselectedColor, com.viewpagerindicator.R.R.lineWidth, com.viewpagerindicator.R.R.gapWidth};
            LinearLayoutICS = new int[]{com.viewpagerindicator.R.R.divider, com.viewpagerindicator.R.R.showDividers, com.viewpagerindicator.R.R.dividerPadding};
            MenuGroup = new int[]{16842766, 16842960, 16843156, 16843230, 16843231, 16843232};
            MenuItem = new int[]{16842754, 16842766, 16842960, 16843014, 16843156, 16843230, 16843231, 16843233, 16843234, 16843235, 16843236, 16843237, 16843375, com.viewpagerindicator.R.R.showAsAction, com.viewpagerindicator.R.R.actionLayout, com.viewpagerindicator.R.R.actionViewClass, com.viewpagerindicator.R.R.actionProviderClass};
            MenuView = new int[]{16842926, 16843052, 16843053, 16843054, 16843055, 16843056, 16843057, 18219084};
            iArr = new int[View_paddingStart];
            iArr[View_android_focusable] = C0282R.attr.play_dtmf;
            Numpad = iArr;
            PagerSlidingTabStrip = new int[]{2130772136, 2130772137, 2130772138, 2130772139, 2130772140, 2130772141, 2130772142, 2130772143, 2130772144, 2130772145, 2130772146};
            ProgressWheel = new int[]{2130772147, 2130772148, 2130772149, 2130772150, 2130772151, 2130772152, 2130772153, 2130772154, 2130772155, 2130772156, 2130772157, 2130772158, 2130772159, 2130772160};
            PullToRefresh = new int[]{2130772161, 2130772162, 2130772163, 2130772164, 2130772165, 2130772166, 2130772167, 2130772168, 2130772169, 2130772170, 2130772171, 2130772172, 2130772173, 2130772174, 2130772175, 2130772176, 2130772177, 2130772178, 2130772179};
            RobotoAutoCompleteTextView = new int[]{2130772180, 2130772181, 2130772182, 2130772183};
            RobotoButton = new int[]{2130772180, 2130772181, 2130772182, 2130772183};
            RobotoCheckBox = new int[]{2130772180, 2130772181, 2130772182, 2130772183};
            RobotoCheckedTextView = new int[]{2130772180, 2130772181, 2130772182, 2130772183};
            RobotoChronometer = new int[]{2130772180, 2130772181, 2130772182, 2130772183};
            RobotoCompoundButton = new int[]{2130772180, 2130772181, 2130772182, 2130772183};
            RobotoDigitalClock = new int[]{2130772180, 2130772181, 2130772182, 2130772183};
            RobotoEditText = new int[]{2130772180, 2130772181, 2130772182, 2130772183};
            RobotoExtractEditText = new int[]{2130772180, 2130772181, 2130772182, 2130772183};
            RobotoMultiAutoCompleteTextView = new int[]{2130772180, 2130772181, 2130772182, 2130772183};
            RobotoRadioButton = new int[]{2130772180, 2130772181, 2130772182, 2130772183};
            RobotoSwitch = new int[]{2130772180, 2130772181, 2130772182, 2130772183};
            RobotoTextClock = new int[]{2130772180, 2130772181, 2130772182, 2130772183};
            RobotoTextView = new int[]{2130772180, 2130772181, 2130772182, 2130772183};
            RobotoToggleButton = new int[]{2130772180, 2130772181, 2130772182, 2130772183};
            SearchView = new int[]{16843039, 16843296, 16843364, com.viewpagerindicator.R.R.iconifiedByDefault, com.viewpagerindicator.R.R.queryHint};
            SlidingDrawer = new int[]{C0282R.attr.direction, C0282R.attr.handle, C0282R.attr.content};
            iArr = new int[View_paddingStart];
            iArr[View_android_focusable] = C0282R.attr.orientation;
            SlidingTab = iArr;
            Spinner = new int[]{16842927, 16843125, 16843126, 16843362, 16843436, 16843437, com.viewpagerindicator.R.R.prompt, com.viewpagerindicator.R.R.spinnerMode, com.viewpagerindicator.R.R.popupPromptView, com.viewpagerindicator.R.R.disableChildrenWhenDisabled};
            SwipeListView = new int[]{2130772187, 2130772188, 2130772189, 2130772190, 2130772191, 2130772192, 2130772193, 2130772194, 2130772195, 2130772196, 2130772197, 2130772198};
            Theme = new int[]{com.viewpagerindicator.R.R.actionDropDownStyle, com.viewpagerindicator.R.R.dropdownListPreferredItemHeight, com.viewpagerindicator.R.R.popupMenuStyle, com.viewpagerindicator.R.R.panelMenuListWidth, com.viewpagerindicator.R.R.panelMenuListTheme, com.viewpagerindicator.R.R.listChoiceBackgroundIndicator};
            TitlePageIndicator = new int[]{16842901, 16842904, 16842964, com.viewpagerindicator.R.R.selectedColor, com.viewpagerindicator.R.R.clipPadding, com.viewpagerindicator.R.R.footerColor, com.viewpagerindicator.R.R.footerLineHeight, com.viewpagerindicator.R.R.footerIndicatorStyle, com.viewpagerindicator.R.R.footerIndicatorHeight, com.viewpagerindicator.R.R.footerIndicatorUnderlinePadding, com.viewpagerindicator.R.R.footerPadding, com.viewpagerindicator.R.R.linePosition, com.viewpagerindicator.R.R.selectedBold, com.viewpagerindicator.R.R.titlePadding, com.viewpagerindicator.R.R.topPadding};
            UnderlinePageIndicator = new int[]{16842964, com.viewpagerindicator.R.R.selectedColor, com.viewpagerindicator.R.R.fades, com.viewpagerindicator.R.R.fadeDelay, com.viewpagerindicator.R.R.fadeLength};
            View = new int[]{16842970, com.viewpagerindicator.R.R.paddingStart, com.viewpagerindicator.R.R.paddingEnd};
            ViewPagerIndicator = new int[]{com.viewpagerindicator.R.R.vpiCirclePageIndicatorStyle, com.viewpagerindicator.R.R.vpiIconPageIndicatorStyle, com.viewpagerindicator.R.R.vpiLinePageIndicatorStyle, com.viewpagerindicator.R.R.vpiTitlePageIndicatorStyle, com.viewpagerindicator.R.R.vpiTabPageIndicatorStyle, com.viewpagerindicator.R.R.vpiUnderlinePageIndicatorStyle};
        }
    }
}
